### ISSUE TITLE
Typescript error on Visual Studio Code

### ISSUE THREAD

**Issue by christosf** [jamauro/method#6]
I get the following error in VS Code when trying to call the methods.

`const { _id, code } = await insertContact({ contact })`

```
This expression is not callable.
  Not all constituents of type '((...args?: any[]) => Promise<Promise<{ _id: string; code: any; }>>) | { pipe: (...fns: Function[]) => { (): any; (...args?: any[]): Promise<Promise<{ _id: string; code: any; }>>; }; }' are callable.ts(2349)
```

**Comment by jamauro** [comment]
Hey, thanks for reporting. I just published a fix in `v1.4.1`

**Comment by christosf** [comment]
Thanks for the quick response. I get a different error now. I get that it has to do with typescript, but I don't use typescript on my project.

![Screenshot 2024-01-20 003016](https://github.com/jamauro/method/assets/28898337/341ca942-e511-465a-9ebf-49365af456e5)

**Comment by jamauro** [comment]
Ok, I made some changes to the typescript declarations and I think it's fixed. Can you do `meteor remove jam:method` and then then `meteor add jam:method@1.4.2-beta.0`. After you confirm it's fixed, I can remove the beta tag. Thanks!

**Comment by christosf** [comment]
> Ok, I made some changes to the typescript declarations and I think it's fixed. Can you do `meteor remove jam:method` and then then `meteor add jam:method@1.4.2-beta.0`. After you confirm it's fixed, I can remove the beta tag. Thanks!

![Screenshot 2024-01-23 091536](https://github.com/jamauro/method/assets/28898337/e0761843-2a32-429e-85dc-2e35153d4e9f)

I get this error when trying to install the package. I had to install jam:method locally in the packages folder to work. The beta version you just released is not available in github to test if it working.

**Comment by christosf** [comment]
> Ok I uploaded the new release to GitHub so you can work with it locally.

The issue is still there. Same error on the beta release

> The `found multiple packages` error is strange. Did you get it when you first tried to add the package? How about when you tried to add it with the explicit version number, i.e. `meteor add jam:method@1.4.2-beta.0`?

Yes the error was there when I first tried to add the package. Also tried with the explicit version number and same result.
I deleted the folder ./meteor/local inside my project and the error is gone now.

**IMPORTANT**
Trying to download your package from Chrome or add it through meteor add command leads to an error because the Windows Defender detects a virus. This is the result:

![Screenshot 2024-01-24 090743](https://github.com/jamauro/method/assets/28898337/f47bb9b3-372c-417c-ad33-e178292156be)

**Comment by jamauro** [comment]
Hmm I haven't been able to reproduce the issue. If you're getting the exact same error as before, then I think something might be cached within Visual Code Studio. Might be worth closing the project and reopening. If you're willing to point me to a GitHub repo, I may be able to investigate further. I can't really reproduce the code that you're using with the `ContactsQueue`.

Since you're not using typescript at all, you could adjust your config files so that the typescript compiler in Visual Code Studio doesn't check your js files or you can use `// @ts-nocheck` at the top of your file. More info [here](https://code.visualstudio.com/docs/nodejs/working-with-javascript#:~:text=You%20can%20use%20%2F%2F%20%40ts,TypeScript%20Version%20command%20to%20check.)

> Trying to download your package from Chrome or add it through meteor add command leads to an error because the Windows Defender detects a virus

Very strange. I have no idea what would cause that. If you have any ideas, let me know.

**Comment by christosf** [comment]
> Hmm I haven't been able to reproduce the issue.

I found out that this error occurs when the extension [Vue Language Features (Volar)](https://marketplace.visualstudio.com/items?itemName=Vue.volar) is installed, which is the official extension from vuejs.org.

Now you will be able to reproduce the issue. Thank you

**Comment by christosf** [comment]
Property 'updated' does not exist on type '{ updated: boolean; } | { pipe: (...fns: Function[]) => (...args?: any[]) => **Promise<Promise<{ updated: boolean; }>>**; }'.

i would suspect the problem is somewhere around this part?
